@ValidadorSenhaSegura_HostAddress = https://localhost:7218
@senha = "mM4 5+678"

### Chamada sem passar a api-version
POST {{ValidadorSenhaSegura_HostAddress}}/api/validate-password
Accept: application/json
Content-Type: application/json
{
    "password": {{senha}}
}
###
# retorna sempre a padrão que no caso é a 
# api-version 2.0


### Chamada passando a api-version 1.0 no header.
POST {{ValidadorSenhaSegura_HostAddress}}/api/validate-password
Accept: application/json
Content-Type: application/json
api-version: 1.0
{
    "password": {{senha}}
}
###
# api-version 1.0

### Chamada passando a api-version 2.0 no header.
POST {{ValidadorSenhaSegura_HostAddress}}/api/validate-password
Accept: application/json
Content-Type: application/json
api-version: 2.0
{
    "password": {{senha}}
}
### 
# api-version 2.0


# Pensando no escopo do banco onde utilizamos o apigateway na frente da api, 
# o uso de api-version via header acaba fazendo sentido, já que a configuração 
# do roteamento fica a cargo de configuração do api gateway, 
# podendo facilmente fazer esse chaveamento.
